[project]
name = "nicegui-vscode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brotli>=1.2.0",
    "fonttools>=4.61.1",
    "nicegui>=3.7.1",
]
